### ISSUE TITLE
const keyword not highlighted

### ISSUE THREAD

**Issue by btipling** [othree/yajs.vim#80] opened 2015-10-24 21:58 UTC
Similar to issue #47 

I've tried a bunch of different color schemes, some even mentioned in other issues here and I can't find one that works to show const as highlighted. let and var work fine.

![vimproblem](https://cloud.githubusercontent.com/assets/249641/10712973/dbe702b0-7a5f-11e5-8b59-ec7735af7774.png)

These are my vundle plugins:

```
Plugin 'scrooloose/nerdtree'
Plugin 'dag/vim-fish'
Plugin 'gmarik/Vundle.vim'
Plugin 'othree/javascript-libraries-syntax.vim',
Plugin 'othree/yajs.vim',
Plugin 'othree/es.next.syntax.vim',
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'Haron-Prime/Antares'
Plugin 'w0ng/vim-hybrid'
Plugin 'Lokaltog/vim-distinguished'
```

The bottom three are the schemes I have tried.

**Comment by othree** [comment] 2015-11-12 06:00
You can try disable plugins one by one to see which one caused this issue.

**Comment by othree** [comment] 2015-11-19 10:26
Since I can't reproduce.
I will close this issue 3 days later if no any more information

**Closed** 2015-12-24 03:45 UTC
